openapi: 3.0.3
info:
  title: TinyTap GameSmith Content Engine
  description: Find Educational games in TinyTap's vast library, Generate TinyTapAI games, and other educational content tools.
  version: 'v1.1.0'
servers:
  - url: https://acedzn-gpt.uc.r.appspot.com
paths:
  /tinytap-games/{query}/{language}/{age}/{page}/{count}:
    get:
      operationId: getTinytapGamesForQueryByLanguageAndAge
      summary: Get TinyTap games for a specific search query by language and age, allows pagination.
      parameters:
        - in: path
          name: query
          schema:
            type: string
          required: true
          description: The search query of the games the user requested.
        - in: path
          name: language
          schema:
            type: string
          required: true
          description: The language abbreviation of the desired games, 'all' for all languages.
        - in: path
          name: age
          schema:
            type: string
          required: true
          description: The age specific for the desired games.
        - in: path
          name: page
          schema:
            type: string
          required: true
          description: Page number for the search, usually start with 1.
        - in: path
          name: count
          schema:
            type: string
          required: true
          description: How many results per page? minimum 5.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tinytapGamesResponse'
  /tinytap-featured-games:
    get:
      operationId: getTinytapFeaturedGames
      summary: Get a list of TinyTap featured games, not specific to any category.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tinytapGamesResponse'
  /tinytap-collections/{language}/{age}/{collections}:
    get:
      operationId: getTinytapCollectionsByLanguageAndAge
      summary: Get TinyTap collections by language and age, allows pagination.
      parameters:
        - in: path
          name: language
          schema:
            type: string
          required: true
          description: The language abbreviation of the desired games, 'all' for all languages.
        - in: path
          name: age
          schema:
            type: string
          required: true
          description: The age specific for the desired games.
        - in: path
          name: collections
          schema:
            type: string
          required: true
          description: Comma seperated list of collections to fetch
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tinytapCollectionsResponse'
  /tinytap-ai-game/{term}:
    get:
      operationId: getTinytapAIGameForTerm
      summary: Used to create dynamic TinyTapAI games. Get AI generated game for any term/topic.
      parameters:
        - in: path
          name: term
          schema:
            type: string
          required: true
          description: The term used for the game creation, must be a real term that follows the 'wikipedia term' rules. the term should use underscores instead of spaces. never use spaces - even not in their encoded form (%20).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tinytapAIGameResponse'
components:
  schemas:
    tinytapAIGameResponse:
      type: object
      properties:
        ready:
          type: boolean
          description: The game generation readiness status. false means the game is still generating and will be ready soon.
        status:
          type: number
          description: The game generation status. 0-game creation started, 1-content creation, 2-audio generation, 3-image search, 4-packing, 5-game is ready to play.
        term:
          type: string
          description: The term used to create the game.
        related_terms:
          type: array
          description: Array of terms related to the game.
          items:
            type: string
        url:
          type: string
          description: The URL to the game player - always return it as a hyperlink to the user.
        game:
          type: object
          description: The TinyTapAI Game object.
          properties:
            title:
              type: string
              description: The game title.
            language:
              type: string
              description: The game's language.
            sections:
              type: array
              description: Array of sections in the game.
              items:
                type: string
            cover_image:
              type: string
              description: The game cover image.
    tinytapGamesResponse:
      type: object
      properties:
        title:
          type: string
          description: Games title.
        description:
          type: string
          description: Games description.
        games:
          type: array
          description: Games Array.
          items:
            $ref: '#/components/schemas/tinytapGameResponse'
    tinytapCollectionsResponse:
      type: object
      properties:
        title:
          type: string
          description: Collections title.
        description:
          type: string
          description: Collections description.
        collections:
          type: array
          description: Collections list.
          items:
            $ref: '#/components/schemas/tinytapCollectionResponse'
    tinytapCollectionResponse:
      type: object
      properties:
        id:
          type: number
          description: The collection id.
        title:
          type: string
          description: The collection title.
        description:
          type: string
          description: The collection description.
        url:
          type: string
          description: Link to the collection.
        content:
          type: array
          description: Collection games list.
          items:
            $ref: '#/components/schemas/tinytapGameResponse'
    tinytapGameResponse:
      type: object
      properties:
        id:
          type: number
          description: The game id.
        title:
          type: string
          description: The game title.
        description:
          type: string
          description: The game description.
        url:
          type: string
          description: Link to the game.
        image:
          type: string
          description: The game cover image.

